pluginManagement {
    repositories {
        google()
        gradlePluginPortal()
        mavenCentral()
    }
}

rootProject.name = "PetFinder-Showcase"
include(":android")
include(":shared")
include(":shared:domain-core")
include(":shared:domain-core:entity")
include(":shared:domain-core:util")
include(":shared:data")
include(":shared:data:infrastructure")
include(":shared:data:infrastructure:network")
include(":shared:data:infrastructure:cache")
include(":shared:data:infrastructure:preferences")
include(":shared:data:repository")
include(":shared:data:repository:pet-detail")
include(":shared:data:repository:home")
include(":shared:domain")
include(":shared:domain:home")
include(":shared:domain:home:data-source")
include(":shared:domain:home:ui-contract")
include(":shared:domain:pet-detail")
include(":shared:domain:pet-detail:data-source")
include(":shared:domain:pet-detail:ui-contract")
include(":shared:domain-core:resources")
include(":android:app")
include(":android:activity")
include(":android:activity")
include(":android:common")
include(":android:common:compose")
include(":android:common:resources")
include(":android:features")
include(":android:features:home")
include(":android:features:pet-detail")
