target 'petsearch-ios' do
  use_frameworks!
  platform :ios, '14.0'
  pod 'Shared', :path => '../petsearch-shared/Shared'
  
  pod 'KMPNativeCoroutinesAsync', '1.0.0-ALPHA-35'
  pod 'KMPObservableViewModelSwiftUI', '1.0.0-BETA-5'
  pod 'SDWebImageSVGCoder'
  pod 'SDWebImageSwiftUI', '2.2.3'
  pod 'ToastSwiftUI'
  pod 'UIPilot', '~> 1.3.1'
end
