target 'petsearch-ios' do
  use_frameworks!
  platform :ios, '14.0'
  pod 'Shared', :path => '../petsearch-shared/Shared'
  
  pod 'KMMViewModelSwiftUI', '1.0.0-ALPHA-14'
  pod 'KMPNativeCoroutinesAsync', '1.0.0-ALPHA-18'
  pod 'SDWebImageSVGCoder'
  pod 'SDWebImageSwiftUI'
  pod 'ToastSwiftUI'
  pod 'UIPilot', '~> 1.3.1'
end
